### ISSUE TITLE
confirmSession: function undefined

### ISSUE THREAD

**Issue by lamm** [colinskow/superlogin#105]
Hello,

I need to use superlogin.confirmSession method to authorize users to use socket.io middleware.
When i try to use the methode, i recieve this error.
TypeError: Property 'confirmSession' of object #<Object> is not a function

I wrote a node.js app to reproduce the issue :
_var express = require('express')
  , bodyParser = require('body-parser')
  , logger = require('morgan')
  , http = require('http')
  , path = require('path')
  , SuperLogin = require('superlogin')
  , errorHandler = require('errorhandler')
  , cookieParser = require('cookie-parser');

var app = express();
// all environments
app.set('port', process.env.PORT || 3000);
app.set('views', __dirname + '/views');
app.set('view engine', 'jade');
app.set('env', 'development');
app.use(cookieParser());
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, 'public')));

// development only
if ('development' == app.get('env')) {
  app.use(errorHandler());
}

var superLoginConfig = {
          dbServer: {
            protocol: 'http://',
            host: 'localhost:5984',
            user: 'admin',
            password: 'password',
            userDB: 'sl-users',
            couchAuthDB: '_users'
          },
          session: {
                // 'redis' or 'memory'
                adapter: 'redis',
                redis: {
                  // If url is supplied, port and host will be ignored
                  url: 'redis://localhost:6379',
                  port: 6379,
                  host: 'localhost',
                  // If a UNIX domain socket is specified, port, host and url
                    // will be ignored
                  options: {},
                }
              },
          mailer: {
            fromEmail: 'email@gmail.com',
            options: {
              service: 'Gmail',
                auth: {
                  user: 'email@gmail.com',
                  pass: 'password'
                }
            }
          },
          userDBs: {
            defaultDBs: {
              shared: ['oneDb']
            }
          }
        }

superlogin = new SuperLogin(superLoginConfig);

app.use('/auth', superlogin.router);
app.get('/test/:token/:password', function(req, res) {
    console.log(req.params.token + ":" + req.params.password);
    console.log(superlogin.confirmSession(req.params.token, req.params.password));
});

var server = http.createServer(app).listen(app.get('port'), function(){
  console.log('Express server listening on port ' + app.get('port'));
});_

Here is the stack of the error :
TypeError: Property 'confirmSession' of object #<Object> is not a function
    at /home/mike/dev/eclipse/workspace/nodeExpress/app2.js:76:25
    at Layer.handle [as handle_request](/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/layer.js:95:5)
    at /home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/index.js:277:22
    at param (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/index.js:349:14)
    at param (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/index.js:365:14)
    at param (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/index.js:410:3)
    at next (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request](/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/index.js:312:13)
    at /home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/index.js:330:12)
    at next (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:95:17)
    at SendStream.error (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/node_modules/send/index.js:275:17)
    at SendStream.onStatError (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/node_modules/send/index.js:392:12)
    at next (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/node_modules/send/index.js:683:16)
    at onstat (/home/mike/dev/eclipse/workspace/nodeExpress/node_modules/express/node_modules/send/index.js:672:14)

I do not know if it is a real bug or if i do not use the method correctly. Can you help me ?
Thanks for you support.

Best Regards.

**Comment by lamm** [comment]
Hello,

After searching in superlogin source code, i found the issue. It is located at line 88 in index.js file.
<confirmSession: user.confirmToken,> have to be replaced by <confirmSession: user.confirmSession,>

Best regards.

**Comment by colinskow** [comment]
Thank you very much for reporting this issue. Meanwhile you can use the `/session` endpoint which will throw an unauthorized if the token is invalid.

**Comment by jwickens** [comment]
Hi is there any update on this ? Would be good to authenticate socket.io with superlogin!

**Comment by colinskow** [comment]
Fixed by #133
