### ISSUE TITLE
Validation failed when seeding database with test users

### ISSUE THREAD

**Issue by markdturner** [colinskow/superlogin#148]
I'm in the process of writing unit tests for my application and need to seed the DB with a couple of users that have different roles so I can test access control on different routes. I'm getting really weird behaviour that manifests itself as a validation failed error with the message:

```
{ error: 'Validation failed',
  validationErrors:
   Error: {"status":404,"name":"not_found","message":"missing","reason":"missing"}
     at /Users/markturner/Workspace/code/vetsens-app/server/node_modules/superlogin/lib/user.js:91:15
     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
   ,
  status: 400 }
```

The weirdest part is that this happens every other time I run the test. So I type gulp test, it fails, I type gulp test a second time it passes. On top of that, if I run my app normally in dev or production mode I get no errors at all. Has anyone seen anything like this before? All I can think of is some kind of race condition or a promise that hasn't resolved.

I've included the Mocha before function to show how I loop over my test users and register them via the register endpoint. The extra fields in there are on the whitelist in the config.

```
before(function(done) {
    
    let agent = request(app);

    async.each(testUsers, function(user, callback) {

        console.log('Registering ' + user.name);

        agent.post('/api/auth/register')
            .send({
                name: user.name,
                email: user.email,
                roles: [user.role],
                password: user.password,
                confirmPassword: user.password,
                verifiedEmail: user.verifiedEmail,
                quicklist: user.quicklist
            })
            .end(function (userRegisterErr, userRegisterRes) {
                if (userRegisterErr) {
                    console.log('ERROR!');
                    console.log(userRegisterErr);
                    return callback(userRegisterErr);
                }
                else {

                    if(userRegisterRes.body.roles){
                        if(userRegisterRes.body.roles.indexOf('admin') !== -1){
                            global.adminSession = {
                                token: userRegisterRes.body.token,
                                password: userRegisterRes.body.password
                            };
                        }

                        if(userRegisterRes.body.roles.indexOf('specialist') !== -1){
                            global.specialistSession = {
                                token: userRegisterRes.body.token,
                                password: userRegisterRes.body.password
                            };
                        }

                        if(userRegisterRes.body.roles.indexOf('nurse') !== -1){
                            global.nurseSession = {
                                token: userRegisterRes.body.token,
                                password: userRegisterRes.body.password
                            };
                        }

                        userIds.push(userRegisterRes.body.user_id);
                    }

                    callback();
                }
            });
    }, function(err) {
        if( err ) {
            console.log('A user failed to register');
        } else {
            console.log('\nAll users have been registered successfully\n\n');
            async.each(testSubjects, function(subject, callback) {
                console.log('Adding ' + subject.name);
                subject._id = subject.name.toLowerCase() + '-' + subject.owner.surname.toLowerCase() + '-' + Date.now();
                app.couch.subjects.put(subject).then(function () {
                    callback();
                }).catch(function (err) {
                    callback(err);
                });
            }, function(err) {
                if( err ) {
                    console.log('A subject failed to be added.');
                    done(err);
                } else {
                    console.log('\nAll subjects have been added successfully\n\n');
                    done();
                }
            });
        }
    });
});
```

**Comment by markdturner** [comment]
I've found that by not deleting the database after the end of all the tests the error does not happen. This still leaves me with an empty test database, but I can live with that as I spin up Docker instances of CouchDB to test with anyway.
