### ISSUE TITLE
Reply Error: Moved

### ISSUE THREAD

**Issue by lightninglu10** [colinskow/superlogin#183]
Hey guys, I'm trying to connect to a Redis cluster on AWS, but it seems like you guys aren't setup for that. Getting an error below:

```
{ ReplyError: MOVED 449 172.31.29.70:6379
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:303:14)
  command: 'PSETEX',
```

And it looks like it doesn't like that I have a cluster. How do I use your package with a Redis cluster?

**Comment by lightninglu10** [comment]
Closing as not planned: filed years ago with no follow-up, and the repo has seen no pushes in years. If this still reproduces on current versions, please re-open with fresh details.
