### ISSUE TITLE
Validation failed

### ISSUE THREAD

**Issue by codeiain** [colinskow/superlogin#193]
Hi am totally need to superlogin and couchdb.

I have been following this [example](https://www.joshmorony.com/part-2-creating-a-multiple-user-app-with-ionic-2-pouchdb-couchdb/) and when ever I call the register endpoint a get via postman I get 
{
    "error": "Validation failed",
    "validationErrors": {},
    "status": 400
}
and my node application returns 

(node:60428) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: {"status":404,"name":"not_found","message":"missing","reason":"missing"}
{ error: 'Validation failed',
  validationErrors: 
   Error: {"status":404,"name":"not_found","message":"missing","reason":"missing"}
       at /Users/iain/Dev/DNDNotebookServer/node_modules/superlogin/lib/user.js:71:15
       at process._tickCallback (internal/process/next_tick.js:103:7),
  status: 400 }

Am currently using couchDB 2.1.1 on mac

**Comment by jay-b** [comment]
Duplicate of https://github.com/colinskow/superlogin/issues/192
