### ISSUE TITLE
Validation Failed

### ISSUE THREAD

**Issue by mike-duran-mitchell** [colinskow/superlogin#198]
Fixed the error from #192 and #193 but now I'm receiving one for a different line in the code for username. I deleted my sl-users database to start anew, but I keep receiving this error.

```
(node:24767) UnhandledPromiseRejectionWarning: Error: [object Object]
[0]     at /home/mike/Desktop/debate/node_modules/superlogin/lib/user.js:50:15
[0]     at <anonymous>
[0]     at process._tickCallback (internal/process/next_tick.js:160:7)
[0] (node:24767) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[0] POST /auth/register 400 74.956 ms - 64
```

Using postman I keep receiving back:

```
{
    "error": "Validation failed",
    "validationErrors": {},
    "status": 400
}
```

When I try to print the promise that is failing, I am getting an empty object as well. 

Additionally, it doesn't look like there is a design doc being added to the 'sl-users' db.

Would be grateful for any solution.

**Comment by mike-duran-mitchell** [comment]
It does look like the lacking of the `_auth` design doc was the problem. After deleting `sl-users` numerous times and trying to add the `_auth` design doc back through `POST` to `/auth/register`, I finally got it to update and include it. 

I'm not really sure what the solution finally ended up being, but aside from trying to figure out the `sl-users` `_auth` design doc issue, it took uninstalling/reinstalling node_modules/ a few times and using both `npm i` and `yarn` to install packages.
