### ISSUE TITLE
Warning in crypto.pbkdf2 with NodeJS 6.

### ISSUE THREAD

**Issue by SukantGujar** [colinskow/superlogin#64]
I recently upgraded to NodeJS 6.1.0, npm 3.8.6. Now Superlogin APIs result in this deprecation warning -

`(node:11324) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest`

**Comment by colinskow** [comment]
OK, I haven't even tested on Node 6 yet. It works for now, but I will be making these adjustments for future versions. The warning is coming from [`couch-pwd`](https://github.com/zeMirco/couch-pwd). I recommend you file an issue there or do a pull request yourself to fix the issue.

**Comment by colinskow** [comment]
I filed an issue here: https://github.com/zemirco/couch-pwd/issues/1

I'll wait a few weeks for the maintainer of this package to fix, otherwise I will fork it

**Comment by SukantGujar** [comment]
Thanks Colin.
On May 16, 2016 2:47 AM, Colin Skow <notifications@github.com> wrote:I filed an issue here: zemirco/couch-pwd#1

I'll wait a few weeks for the maintainer of this package to fix, otherwise I will fork it

**Comment by numerized** [comment]
Hi guys, thanks for the ticket,

Is it blocking, because I can register user and I can't connect with the login route ?

**Comment by colinskow** [comment]
@numerized that problem should have nothing to do with the Crypto warning. It will work fine until Node 7.

What problem are you having with the login route?

**Comment by numerized** [comment]
I simply didn't know that username has to be in small letters to be accepted. I could create my account with capital letters in the username with a rest client but I couldn't login with the same credential accepted before ! now I create my usernames in small it works well.

**Comment by antonyRoberts** [comment]
@colinskow What is the status of this? Node 7 has been out for a while

**Comment by EuAndreh** [comment]
@antonyRoberts https://github.com/zemirco/couch-pwd/pull/2

**Comment by sandro-pasquali** [comment]
This now breaks in Node 8. Superlogin throws now -- no longer just deprecated. It is a straight failure now. 

```
TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:635:11)
    at Object.exports.pbkdf2 (crypto.js:623:10)
    at Object.exports.hash (/.../node_modules/couch-pwd/index.js:41:12)
    at Object.exports.verifyPassword (/.../node_modules/superlogin/lib/util.js:37:10)
    at /.../node_modules/superlogin/lib/local.js:55:18
    at <anonymous>
```
Can we get this updated? Also, the npm module version hasn't been updated in quite a while and it would be good to get some recent fixes in a distributable package form.

Thanks!

**Comment by sandro-pasquali** [comment]
ps. couch-pwd is a tiny little package with no non-native deps (https://github.com/zemirco/couch-pwd/blob/master/index.js) so it maybe can just be copied into a core superlogin file, rather than waiting for it to be updated/published?

**Comment by peteruithoven** [comment]
Relevant: https://github.com/colinskow/superlogin/issues/167

**Comment by sandro-pasquali** [comment]
I'd be happy to do this (and some other things) if I could be a contributor.

**Comment by natew** [comment]
Running into this as well. It looks like the fix is already in this repo, can we get a publish?

**Comment by palejabhargav** [comment]
You can add following dependency in your package.json for npm to fetch dependency directly from github repo which already has the fix.
`"couch-pwd": "zemirco/couch-pwd"`

**Comment by klues** [comment]
I had the same issue and now use the fork https://www.npmjs.com/package/@sensu/superlogin which already includes the fixed version of `couch-pwd` and also other updated dependencies like pouchdb `6.4.3` instead of `5.3.2` in the current release of this repository.

However it would be great if a new release of this "official" repository with fixed/updated dependencies would be published or another fork would be declared as new "official" repository where development continues. At the moment it seems to be quite a mess.

**Comment by jaredthirsk** [comment]
\>>> **Superlogin is broken / dead** <<<, as far as I can tell, unless and until couch-pwd gets replaced.  I see sen-su made an updated fork: https://github.com/sen-su/couch-pwd, but it looks like he has an entirely new fork of superlogin, so I will check that out.  Adios, dead project.

**Comment by colinskow** [comment]
Sounds good. I honestly stopped using CouchDB, so I haven't had any resources to devote to maintaining it. If sen-su would like to take over the official package I would be happy to hand over the repo and NPM package.

**Comment by fynnlyte** [comment]
I've also made a fork of superlogin, updated all dependencies and some tests (Travis CI for node 10 & Snyk scans) and refactored it a bit:
https://github.com/LyteFM/superlogin 
I also considered to publish it on npm, but would of course be nicer to contribute to the official package if he'd like to work on it.

**Comment by colinskow** [comment]
@LyteFM could you please make a pull request with your updates?
